### ISSUE TITLE
License

### ISSUE THREAD

**Issue by helgee** [oliverphilcox/Keplers-Goat-Herd#1]
Hi,

Thanks for putting your code out there! Unfortunately the repo lacks a LICENSE.md file and is thus not "open source" but "source available" and cannot be reused or remixed without your authorization. Is that intended?

Cheers,
Helge

**Comment by astrojuanlu** [comment]
I don't want to be pushy with this topic as it's a controversial one, but while we are at it, may I suggest using a permissive license, such us MIT? https://choosealicense.com/licenses/mit/

**Comment by oliverphilcox** [comment]
Thanks for pointing this out - was certainly an omission. I've added an MIT license now!
